### ISSUE TITLE
WiFi.getTime() is returning 1 day older day on MKR1000

### ISSUE THREAD

**Issue by LRagji** [arduino-libraries/WiFi101#119]
Found a interesting defect WiFi.getTime() is returning  one day previous to actual date, another thing i could not find is where are we making set time call (m2m_wifi_set_sytem_time) so that i can check if the source is returning correct time.?

Any help would be appreciated on MKR1000 testing with help of http://www.epochconverter.com/ site and RTCZero lib

**Comment by sandeepmistry** [comment]
Hi @LRagji,

I've submitted pull request #120 to fix this, could you please try out the change?

If all is good, it will be included in the next WiFi101 library release.

**Comment by LRagji** [comment]
@sandeepmistry This works with MKR1000 just tested it Thanks

**Comment by sandeepmistry** [comment]
@LRagji thanks for trying it out, I've merged the fix in #120, so it will part of the next WiFi101 library release.

**Comment by sandeepmistry** [comment]
v0.12.0 has been released today with the latest changes from master, which includes the fix.
