### ISSUE TITLE
Problem when running WiFiClient and WiFiServer at the same time

### ISSUE THREAD

**Issue by sontono** [arduino-libraries/WiFi101#127]
Hi,
I am running library on MKR1000 with IP 192.168.0.37.
I start a WiFiServer (ws). Afterwards, I create a WiFiClient (wc) and connect it to an external IP and port (192.168.0.18:8181).
The problem now is that ws.available() returns the client wc as it was a client connected to the own server.
This is the full code:

```
#include <WiFi101.h>

WiFiClient wc;
WiFiServer ws(5000);

void setup() {
	// Open serial port
	Serial.begin(9600);

	// Connect to wifi
	WiFi.begin(ssid, key);
	int i = 0;
	while (WiFi.status() != WL_CONNECTED && i < 5) {   
		delay(500);
		Serial.print(".");
		i++;
	}
	delay(100);
	if (WiFi.status() != WL_CONNECTED) {
		Serial.println(F("Error: WiFi not connected!"));
	}
	
	// Start server
	ws.begin();

	// Connect client
	wc.connect("192.168.0.18", 8181);
	
	// Test
	if (ws.available()) Serial.print("UNEXPECTED: client connected!");
	else Serial.println("NO client connected");
}

void loop() {
	delay(1000);
}
```
Thanks

**Comment by sandeepmistry** [comment]
Hi @sontono,

Thanks for letting us know about this issue, and the excellent issue report!

I've submitted pull request #128 to resolve this, could you please try out the change?

**Comment by sontono** [comment]
As commented in #128, that pull request fix this issue

**Comment by sandeepmistry** [comment]
v0.12.0 has been released today with the latest changes from master, which includes the fix.

**Comment by sontono** [comment]
Great!!. Thank you very much
