### ISSUE TITLE
Feature request: mDNS / DNS-SD (Bonjour / Zeroconf)

### ISSUE THREAD

**Issue by toqduj** [arduino-libraries/WiFi101#131]
It would be very useful for the IoT (in particular for the MKR1000) if we had options for advertising services on the MKR1000, and/or finding advertised services on local networks. I understood this requires detailed access to the WiFi chip functionality, which Wifi101 might have. 
Example for ethernet: 
https://github.com/TrippyLighting/EthernetBonjour

**Comment by sandeepmistry** [comment]
Hi @toqduj,

We've created a fork of EthernetBonjour which supports both Ethernet and WiFi101 capable boards: https://github.com/arduino-libraries/ArduinoMDNS

Please let us know if you have any feedback before we make an initial release for the Library Manager.

**Comment by toqduj** [comment]
Awesome, thanks!

**Comment by toqduj** [comment]
Awesome, I'll have to give it a try!

**Comment by sandeepmistry** [comment]
@toqduj great, the library is also now available in the IDE's Library Manager, just searcher for ArduinoMDNS.

**Comment by toqduj** [comment]
I don't see it in the library manager...

**Comment by toqduj** [comment]
... any chance it'll be merged back with the TrippyLighting branch? They've got one more fix that might be important...

**Comment by sandeepmistry** [comment]
@toqduj could you please open an issue here for this: https://github.com/arduino-libraries/ArduinoMDNS

We've enabled the issue tracker. What specific fix are you referring to?
