### ISSUE TITLE
using gettime() with a static IP address

### ISSUE THREAD

**Issue by providersolutions** [arduino-libraries/WiFi101#140]
any reason we can't use a static address and gettime() together?

gettime() always returns a zero if a WiFi.config(ip) is called prior to the WiFi.begin()

if i comment out the .config, gettime() works fine.

**Comment by sandeepmistry** [comment]
@providersolutions I believe you'll also need to provide the IP address of a DNS server:

```
WiFi.config(local_ip, dns_server);
```

Otherwise the WINC1500 firmware will not be able to resolve the NTP servers IP address via DNS.

Can you please try this?

**Comment by providersolutions** [comment]
Works!  thanks, been trying to figure it out for most of the day...thanks for the quick reply!

**Comment by sandeepmistry** [comment]
Your welcome, glad I could help!

I'm going to close this issue now. @akash73 what do you think about updating the WiFi101 library reference to mention `WiFi.getTime()` requires a DNS server set?

**Comment by providersolutions** [comment]
i think that would be very helpful to others.

**Comment by mamama1** [comment]
you gonna explain the internet now in the reference?

**Comment by providersolutions** [comment]
good documentation should explain dependencies and assumptions.   it is not obvious why, with a static address specified in “x.x.x.x” format, begin() works without a DNS specified in config() but gettime() does not.


gettime():

when using config() to specify a static ip address, gettime() requires that config() also specify a DNS address.

   
     
that gonna work for ya?
