### ISSUE TITLE
Get all BSSID around and their channels

### ISSUE THREAD

**Issue by gmag11** [arduino-libraries/WiFi101#141]
Current library version does not implement a method to get BSSIDs and channels after a scan is called, only SSIDs and RSSIs are allowed.

I've implemented them and will make a pull request.

**Comment by sandeepmistry** [comment]
Hi @gmag11,

I've submitted #143 for this, it's similar to #142 which you submitted, however it has:

* a change to the `BSSIS` API to pass a buffer in like `macAddress` and `BSSID(bssid)`.
* the styling is more consistent with the rest of the code in the WiFi101 library.

Could you please try it out and report your feedback?

**Comment by gmag11** [comment]
Hi @sandeepmistry 

I think a function the form as `uint8_t* BSSID(uint8_t pos)` is consistent with already existing `char* SSID(uint8_t pos)`. 
What is pointer parameter in `uint8_t* BSSID(uint8_t pos, uint8_t* bssid)` intended for?

**Comment by sandeepmistry** [comment]
> What is pointer parameter in uint8_t* BSSID(uint8_t pos, uint8_t* bssid) intended for?

It's for the 6 byte array the caller wants to store the BSSID in, please see:
 * https://www.arduino.cc/en/Reference/WiFi101BSSID
 * https://www.arduino.cc/en/Reference/WiFi101MACAddress

> I think a function the form as uint8_t* BSSID(uint8_t pos) is consistent with already existing char* SSID(uint8_t pos).

Right, but `char* SSID(uint8_t pos)` returns a C string instead of a `uint8_t*`.

**Comment by RedDragon9** [comment]
I would also like to be able to get the channel of the Wifi networks after a scan.

**Comment by gmag11** [comment]
With my code you can get bssid and channel of all surrounding networks, besides ssid and rssi that were already possible. Check my fork and share your results, thanx.

**Comment by RedDragon9** [comment]
Could you post the link to the code please.

**Comment by gmag11** [comment]
https://github.com/gmag11/WiFi101 Select scan_info branch

**Comment by RedDragon9** [comment]
I added the library but can you tell me the code I need to add to the scan networks program to show the channal and bssid because I can't seem to get it to work or do you have a scan network explain that includes that?

**Comment by gmag11** [comment]
It's used in this code https://github.com/gmag11/ESPWifiLocation/blob/master/src/WifiLocation.cpp#L19

**Comment by RedDragon9** [comment]
Ok thanks, I got it working. I found I still had the wifi101 library installed and that why the code wouldn't work.

**Comment by agdl** [comment]
closed via https://github.com/arduino-libraries/WiFi101/pull/146
