### ISSUE TITLE
Example of receive post data

### ISSUE THREAD

**Issue by jdneo** [arduino-libraries/WiFi101#151]
Hi,

I have a WINC1500 which acts as a server and need to receive the form post data from other client. After a long time searching, I failed to find the example of this senario.

Currently, if I use WiFiClient::read() method, I can only receive the request header part. The form-data part is missing. Is there any way to receive the post data?

Thank you!

**Comment by sandeepmistry** [comment]
@jdneo please share the sketch you are using.

**Comment by jdneo** [comment]
Hi sandeepmistry,

Sorry for my late reply. The sketch is listed as follows:

```
#include <SPI.h>
#include <WiFi101.h>

int led = LED_BUILTIN;
const String WIFI_CONFIG_HEAD = "GET /setting?";

char ssid[] = "wifi101-network"; // created AP name
char pass[] = "1234567890";      // AP password (needed only for WEP, must be exactly 10 or 26 characters in length)
int keyIndex = 0;                // your network key Index number (needed only for WEP)

int status = WL_IDLE_STATUS;
WiFiServer server(80);

void setup()
{
  Serial.begin(9600);
  while (!Serial)
  {
    ; 
  }

  Serial.println("Access Point Web Server");

  pinMode(led, OUTPUT); // set the LED pin mode

  if (WiFi.status() == WL_NO_SHIELD)
  {
    Serial.println("WiFi shield not present");
    while (true)
      ;
  }

  Serial.print("Creating access point named: ");
  Serial.println(ssid);


  status = WiFi.beginAP(ssid);
  if (status != WL_AP_LISTENING)
  {
    Serial.println("Creating access point failed");
    while (true)
      ;
  }

  delay(10000);

  server.begin();
}

void loop()
{
  if (status != WiFi.status())
  {
    status = WiFi.status();
  }

  WiFiClient client = server.available(); 

  if (client)
  {  
    Serial.println("new client"); 
    String currentLine = "";    
    while (client.connected())
    { 
      if (client.available())
      {                         
        char c = client.read();
        Serial.write(c);
        if (c == '\n')
        { 
          if (currentLine.length() == 0)
          {
           
            client.println("HTTP/1.1 200 OK");
            client.println("Content-type:text/html");
            client.println();

            client.println("<!DOCTYPE HTML>");
            client.println("<html>");
            client.println("<p>Hello from Feather M0!<P/><br/>");

            client.println("<form method='get' action='setting'>");

            client.println("<label>SSID:</label>");
            client.println("<input name='ssid' length=64 type='text'/><br/><br/>");

            client.println("<label>PASS:</label>");
            client.println("<input name='pass' length=64 type='password'/><br/><br/>");

            client.println("<input type='submit'/>");

            client.println("</form>");
            client.println("</html>");

            client.println();
            break;
          }
          else
          {
            if (currentLine.startsWith(WIFI_CONFIG_HEAD))
            {
              /* parse the get request data here*/
              break;
            }
            currentLine = "";
          }
        }
        else if (c != '\r')
        {                   
          currentLine += c; 
        }
      }
    }
    client.stop();
    Serial.println("client disconnected");
  }
}
```

It's very similar with the [sample code](https://github.com/arduino-libraries/WiFi101/blob/master/examples/AP_SimpleWebServer/AP_SimpleWebServer.ino). Currently the form using get action and I can successfully parse the request. But when I change the action field to _POST_

`client.read();`

can only get the request header part. The body part(form data) is missing. Is there any way to parse the post request?

Thanks

**Comment by sandeepmistry** [comment]
@jdneo here's a modified version:

```arduino
#include <SPI.h>
#include <WiFi101.h>

int led = LED_BUILTIN;
const String WIFI_CONFIG_HEAD = "GET /setting?";

char ssid[] = "ssid"; // ssid
char pass[] = "pass";      // password
int keyIndex = 0;                // your network key Index number (needed only for WEP)

int status = WL_IDLE_STATUS;
WiFiServer server(80);

void setup()
{
  Serial.begin(9600);
  while (!Serial)
  {
    ; 
  }

  Serial.println("POST Web Server");

  pinMode(led, OUTPUT); // set the LED pin mode

  if (WiFi.status() == WL_NO_SHIELD)
  {
    Serial.println("WiFi shield not present");
    while (true)
      ;
  }

  Serial.print("Connecting to access point named: ");
  Serial.println(ssid);


  status = WiFi.begin(ssid, pass);
  if (status != WL_CONNECTED)
  {
    Serial.println("Connecting to AP failed");
    while (true)
      ;
  }

  IPAddress ip = WiFi.localIP();
  Serial.print("Connected to AP, IP is: ");
  Serial.println(ip);

  delay(10000);

  server.begin();
}

void loop()
{
  if (status != WiFi.status())
  {
    status = WiFi.status();
  }

  WiFiClient client = server.available(); 

  if (client)
  {  
    Serial.println("new client"); 
    String currentLine = "";    
    while (client.connected())
    { 
      if (client.available())
      {                         
        char c = client.read();
        Serial.write(c);
        if (c == '\n')
        { 
          if (currentLine.length() == 0)
          {
// NEW ///////////////////////////////////////////
            String requestBody;

            while (client.available()) {
              requestBody += (char)client.read();
            }

            if (requestBody.length()) {
              Serial.println("Request body = ");
              Serial.println(requestBody);
              Serial.println();
            }
////////////////////////////////////////////////            
           
            client.println("HTTP/1.1 200 OK");
            client.println("Content-type:text/html");
            client.println();

            client.println("<!DOCTYPE HTML>");
            client.println("<html>");
            client.println("<p>Hello from Feather M0!<P/><br/>");

            client.println("<form method='post' action='setting'>");

            client.println("<label>SSID:</label>");
            client.println("<input name='ssid' length=64 type='text'/><br/><br/>");

            client.println("<label>PASS:</label>");
            client.println("<input name='pass' length=64 type='password'/><br/><br/>");

            client.println("<input type='submit'/>");

            client.println("</form>");
            client.println("</html>");

            client.println();
            break;
          }
          else
          {
            if (currentLine.startsWith(WIFI_CONFIG_HEAD))
            {
              /* parse the get request data here*/
              break;
            }
            currentLine = "";
          }
        }
        else if (c != '\r')
        {                   
          currentLine += c; 
        }
      }
    }
    client.stop();
    Serial.println("client disconnected");
  }
}
```

There's nothing wrong with the WiFi101 library, the request body is available after the headers are sent and the end of the headers are indicated by a blank like.

**Comment by jdneo** [comment]
Thank you @sandeepmistry. Seems I asked a stupid question  ;-)

**Comment by DannyV1** [comment]
I found that I needed to waste the first hidden (NULL) byte:
(I'm using the String variable postData instead):
`
    ....
    String postData = "";
    //WASTE THIS BYTE: should be null
    char nByte = (char)client.read();
    if (nByte != '\0') {
        postData = nByte;
    }
    while (client.available()) {
        postData += (char)client.read();
    }
    if (postData.length()) {
      ....
`

Regards,
Danny

**Comment by robertsonadams** [comment]
May I ask, what does the corresponding HTML form look like that takes in the posted data?

**Comment by DannyV1** [comment]
Hi Robert,
Firstly I made a mistake on my previous post, the section labelled "WASTE THIS BYTE" is an error.
Here's an excerpt of my code, and a picture of my 'Whistle' button at the end: 
<pre><code>
//Process hidden POST data
void processPostData(String pstd,  int cLen)
{
const byte POSTBUFF_SIZE = 60;
char  postBuff[POSTBUFF_SIZE + 1];
const uint8_t EB_LEN = 180;
char ErrBuff[EB_LEN + 1];
char *pos = NULL;
char cmdState;
uint8_t pbLen = pstd.length();
uint8_t mainStrLen = strlen(MAIN_STR);


    memset(postBuff, 0, POSTBUFF_SIZE);
    for (int ii = 0; ii < cLen && ii < POSTBUFF_SIZE; ii++) {
        if (ii >= pbLen) {
            if (ii < cLen - 1) {
                snprintf(ErrBuff , EB_LEN,
                    "Not all POST data rxed [%s] (%d of %d)",
                                postBuff, ii, cLen);
                StatusbarStr = ErrBuff;
                return;
            }
            break;
        }
        postBuff[ii] = pstd[ii];
        postBuff[ii+1] = '\0';
    }

    if ((pos=strstr(postBuff, MAIN_STR)) != NULL)   {
        //MAIN_=H
        pos += (mainStrLen +1);
        if (pos != NULL) {
            cmdState = *pos; //"H"
            //give web page feedback that command has been processed
            StatusbarStr = "Status: ";
            StatusbarStr += cmdState;
            StatusbarStr += "  ";
            switch (cmdState) {
                case 'H':
                //Whistle
                    digitalWrite(LED_PIN, HIGH);
                    digitalWrite(WHISTLE_PIN, HIGH);
                    delay(100);
                    digitalWrite(WHISTLE_PIN, LOW);
                    delay(400);
                    digitalWrite(LED_PIN, LOW);
                    //remove web statusbar msg after 30 secs
                    //(handled in loop)
                     cmdRefreshed = millis();
                    break;
                case 'L':
                    break;
                case 'C':
                    break;
                case 'B':
                    break;
            } //switch
        } //if (pos != NULL) {
    } //pos=strstr(postBuff, MAIN_STR
}


// called from inside loop()
void checkForClient()
{
bool isPost = false;
bool finished = false;
int contentLen = 0;
long int count = 32000L; //timeout in case client locks up

    WiFiClient client = server.available();   // listen for incoming clients

    if (client) {                             // if you get a client,
#ifdef DEBUG1
        Serial.println("new client");
#endif

        String currentLine = "";                // make a String to hold incoming data from the client
        // loop while the client's connected
        while (client.connected()) {
            // if there's bytes to read from the client,
            if (client.available()) {
                char c = client.read();             // read a byte, then

#ifdef DEBUG2
                Serial.write(c);  // print it out the serial monitor
#endif  //DEBUG2
                if (c == '\n') {
                    // if the current line is blank, you got two newline characters in a row.
                    // that's the end of the client HTTP request, so send a response:
                    if (currentLine.length() == 0) {
                        if (finished && isPost) {
                            // get hidden POST data
                            String postData = "";

                            //wait for up to 2 secs for data to start
                            int timeOut = 2000;
                            do {
                                while (!client.available()) {
                                    delay(1);
                                    if ((--timeOut) <= 0)
                                        break;
                                }
                                while (client.available()) {
                                    postData += (char)client.read();
                                }
                            } while ((timeOut > 0) && (postData.length() < contentLen));

                            if (postData.length()) {
#ifdef DEBUG1
                                Serial.println("postData = [");
                                Serial.println(postData);
                                Serial.println("]");
#endif  //DEBUG1
                                //Process POST data
                                processPostData(postData, contentLen);
                            } else {
                                StatusbarStr = "No POST data available, bytes expected: ";
                                StatusbarStr +=  contentLen;
                            }
                        } /*else  if (isGet && finished) {*/
                        //restart timout if data received
                        count = 32000L;

                        client.println("HTTP/1.1 200 OK");
                        client.println("Content-Type: text/html");
                        client.println("Connection: close");
                        client.println("Refresh: 10");
                        client.println();
                        client.println("<!DOCTYPE HTML>");
                        client.println("<html>");
                        client.print(F("<head>"));
                        client.println(F("<style>"));
                        client.println(F("		h1 {"));
                        client.println(F("			font-size: 180%;"));
                        client.println(F("			color: blue;"));
                        client.println(F("			margin: 0 0 10px 0;"));
                        client.println(F("		}"));
                        client.println(F("		input {"));
                        client.println(F("			font-size: 200%;"));
                        client.println(F("			color: blue;"));
                        client.println(F("			height: 150px;"));
                        //client.println(F("			width: 100px;"));
                        client.println(F("		}"));
                        client.println(F("		table {"));
                        client.println(F("			font-size: 120%;"));
                        client.println(F("			color: blue;"));
                        client.println(F("		}"));
                        client.println(F("</style>"));
                        client.println(F("</head>"));
                        // the content of the HTTP response follows the header:
                        client.println(F("<body  style=\"font-size:150%\">"));
                        client.print(F("<div align='center'>"));
                        client.print(F("<h1>{insert Page Heading}</h1>"));
                        client.print(F(""));
                        //Button 1: in a 1 row table
                        client.print(F("<table border='2'  cellspacing='2'  cellpadding='2'  bordercolor='#336699' >"));
                        client.print(F("<tr><td>"));
                        client.print(F("<form action='/' method='POST'>"));
                        client.print(F( " <input type='hidden' name='MAIN_' value='H'>"));
                        client.print(F( " <input type='submit' value='Whistle'>"));
                        client.print(F( "</form>"));
                        client.print(F("</td>"));
                        client.print(F("<td>"));
                        //More buttons .....

                        client.print(F("</td>"));
                        //end of table
                        client.println(F("</tr></table></div>"));
                        //end of web page
                        client.println(F("</footer>"));
                        client.println(F("</body></html>"));

                        // The HTTP response ends with another blank line:
                        client.println();
                        // break out of the while loop:
                        break;
                    } else {      // if you got a newline, then clear currentLine:
                        if (!finished && isPost) {
                            if (currentLine.startsWith("Content-Length:")) {
                                char *p =&(currentLine[15]);
                                while (p != NULL  && *p == ' ' ) p++;
                                if (p != NULL) {
                                    contentLen = atoi((const char *)p);
#ifdef DEBUG1
                                    Serial.print(F("Content-Length= "));
                                    Serial.println(contentLen);
#endif //DEBUG1
                                    if (contentLen > 0) {
                                        finished = true;
                                    } else {
                                        isPost = false;
                                    }
                                }
                            }
                        }
                        currentLine = "";
                    }

                } else if (c != '\r') {    // if you got anything else but a carriage return character,
                    currentLine += c;      // add it to the end of the currentLine
                }
                if (!finished  && currentLine.startsWith("POST")) {
#ifdef DEBUG2
                    Serial.println(F("POST "));
#endif //DEBUG2
                    isPost = true;
                }
            } //if (client.available(
            if ((count--) <= 0) {
                Serial.println("Timeout!");
                break;
            }
        } //while (client.connected()

        // close the connection:
        delay(2); // give the web browser time to receive the data
        client.stop();
#ifdef DEBUG1
        Serial.println("client disconnected");
#endif
    } //if (client
} //checkForClient
![button](https://cloud.githubusercontent.com/assets/9337225/25310091/7edae0f8-281b-11e7-8abb-9062289b3a5d.jpg)


</pre></code>
