### ISSUE TITLE
lockup issue

### ISSUE THREAD

**Issue by tonton81** [arduino-libraries/WiFi101#177]
dont know if this is a teensy 3.5 issue or not, im able to make the adafruit winc1500 work on one 3.5 but not another, on both SPI0 and SPI1. The problem is when it doesn't work, it will lock up the entire mcu code
(block forever)

try to boot the MCU without the winc1500 connected, you will see a complete lockup.
If the Winc1500 ever fails, this can lead to disastrous results

**Comment by sandeepmistry** [comment]
Hi @tonton81, What version of the WiFi101 library are you using? Could you also please share a minimal sketch that locks up?

**Comment by tonton81** [comment]
latest one off this github, using a teensy 3.5, its been a long while so ill have to look for the code in my history sketches

**Comment by sandeepmistry** [comment]
Hi @tonton81,

I suggest you contact Adafruit customer support, we cannot reproduce the issue with a MKR1000 or WiFi101 shield.

If it turns out to be an issue with the library, please re-open the issue with more details.
