### ISSUE TITLE
WiFi101 TCP data corrupted on MKR1000 after reading large number of bytes

### ISSUE THREAD

**Issue by Sudeshna19** [arduino-libraries/WiFi101#184]
I am using MKR1000 as WiFi TCP server and an application in Windows7 machine as WiFi TCP client. The idea is to connect the client to TCP server and send many bytes (~ 200 bytes). TCP server reads the received data and sends it back to client. I am using Hercules SETUP utility 3.2.8 (http://www.hw-group.com/products/hercules/index_en.html) as the TCP client on Windows.

The code is below:
```
 #include <SPI.h>
 #include <WiFi101.h>

 int configureSuccess = WL_IDLE_STATUS;
 char ssid[] = "TP-LINK_POCKET_3020_C051E6"; //  your network SSID (name)
 char pass[] = "83378669";    // your network password (use for WPA, or use as key for WEP)
 WiFiServer server(40000);
 uint8_t alreadyConnected = false; 
 uint8_t data1;
 void setup() {
    Serial.begin(57600);
   // Serial1.begin(57600);
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    while ( configureSuccess != WL_CONNECTED) {
        configureSuccess = WiFi.begin(ssid, pass);
        unsigned long startMillis  = millis();
        while(millis()- startMillis < 10000)
                        {
                        };
       }
              
         server.begin();
      for(int trialcount=0;trialcount<5;trialcount++)
      {
          if(Serial)
          {
              break;
          }else
          {
              unsigned long startMillis  = millis();
              while(millis()- startMillis < 1000)
                        {
                        };
          }
      }
      
      
      if (configureSuccess==WL_CONNECTED)
       { 
         IPAddress ip = WiFi.localIP();
         Serial.print("<<<IP address: ");
         Serial.print(ip);  
         Serial.println(">>>");            
      }
     else
     {
         // If the Configuration failed,relay back the error message.
         Serial.println("<<< IP address :Failed to configure. >>>");
     }

     Serial.println("Server: started");
}

void loop() {
   // wait for a new client:
   int avlBytes = 0;
   int st = 0;
   Serial.println("loop");

   
  WiFiClient client1 = server.available();
  if (!client1){
    Serial.println("Server: No client");
  }

    avlBytes = client1.available();
    if(avlBytes >= 1){
         st = client1.read(&data1,1);  
                
         switch(data1){
          case 'A': Serial.println("rcvd A");     break;
          case 'B': Serial.println("rcvd B");     break;
          case 'C': Serial.println("rcvd C");     break;
          case 'D': Serial.println("rcvd D");     break;
          case 'E': Serial.println("rcvd E");     break;
          case 'F': Serial.println("rcvd F");     break;
          case 'G': Serial.println("rcvd G");     break;
          case 'H': Serial.println("rcvd H");     break;
          case 'I': Serial.println("rcvd I");     break;
         }
         Serial.println("Server sending..");
         server.write("Sent ");
         if (data1 == 'A'){
         server.write("**---S--");
         server.write(data1);
         }
         else if (data1 == 'I'){         
         server.write(data1);
         server.write("--X---**");
         }
         else
         server.write(data1);
      }
    else{
      Serial.println("Server: no data");
      }
    
  
 unsigned long startMillis  = millis();
  while(millis()- startMillis < 500)
                        {
                        };

}
```
Attached below is the snapshot of the data sent and received using Hercules Utility
![hostreceive](https://user-images.githubusercontent.com/29605115/28016473-1764f2a6-6592-11e7-86d6-0bf3983260e4.PNG)

I sent a repeating pattern of ABCDEFGHI (7 times in 3 rows) resulting in ~210 bytes. In the attached snapshot you can see in area marked under red that the data read from TCP buffer gets corrupted after reading some 100 bytes. I receive something as:
Sent ÎSent YSent óSent ½Sent Sent 'Sent ÝSent WSent Sent Sent ÛSent ¹Sent 9Sent Sent ÊSent ÆSent  Sent eSent Sent Sent þSent aSent ôSent °Sent sSent îSent øSent Sent /Sent YSent ¯Sent ¼Sent ÖSent §Sent ´Sent ¥Sent ÕSent ¨Sent _Sent Sent 3Sent ÎSent vSent 'Sent ºSent 2Sent ¡Sent ùSent îSent ÆSent {FF}Sent WSent Sent i

**Comment by sandeepmistry** [comment]
Hi @Sudeshna19,

I've tried to reproduce this using `netcat` on macOS, it seems fine to me:

`
$ nc 10.0.1.63 40000
ABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJ
Sent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent **---S--ASent BSent CSent DSent ESent FSent GSent HSent I--X---**Sent JSent 
`

Could you please try again and use Wireshark to capture the data transfer, then upload a saved capture here?

**Comment by sandeepmistry** [comment]
Also, please provide the output of the sketch to the serial monitor.

**Comment by Sudeshna19** [comment]
@sandeepmistry 
I am attaching the Wireshark data and data of TCP Client on Host . For Serial monitor output I had to take a screenshot so could not save the entire output.
![serial_monitor_out](https://user-images.githubusercontent.com/29605115/32218068-c52a0d48-be4f-11e7-8597-8f95a228da09.PNG)
[TCPClient_data.txt](https://github.com/arduino-libraries/WiFi101/files/1430242/TCPClient_data.txt)
[wireshark_capture.zip](https://github.com/arduino-libraries/WiFi101/files/1430246/wireshark_capture.zip)

I have tried on Windows10 this time. Same issue. Let me know if you need further info.

**Comment by Sudeshna19** [comment]
In the above test IP addresses are as below:
MKR1000 - 192.168.0.101   port 40000
Host (Win10 application) - 192.168.0.100
Router - 192.168.0.254

**Comment by sandeepmistry** [comment]
So in the Wireshark trace, the first two TCP packets have 99 bytes of data: `ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHI`

<img width="1347" alt="screen shot 2018-01-02 at 12 08 55 pm" src="https://user-images.githubusercontent.com/1163840/34492495-d97b5814-efb5-11e7-9ccb-a189ca8c3060.png">

This is followed by 3 TCP packets contain 1 byte with value `0x01`:

<img width="1347" alt="screen shot 2018-01-02 at 12 08 38 pm" src="https://user-images.githubusercontent.com/1163840/34492513-ef0b6836-efb5-11e7-9876-223b445a3b23.png">


@Sudeshna19 could you please provide the exact sketch you used to produce https://github.com/arduino-libraries/WiFi101/issues/184#issuecomment-340713740, it seems to differ from the sketch provided in https://github.com/arduino-libraries/WiFi101/issues/184#issue-241700616.

Please also try the master version of this library, it includes some changes from pull request #204 - just want to confirm the issue still exists with these changes, or if they are resolved.

**Comment by sandeepmistry** [comment]
I'm closing this for now due to lack of feedback.
