### ISSUE TITLE
SSL client connect fails on ports other than 443 for Adafruit Feather M0

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [arduino-libraries/WiFi101#187]
The Adafruit Feather M0 cannot make SSL connections except on port 443, which breaks mqtt and amqp protocols on Azure IoT. Attached is a failure case with the interesting code on line 86. To run the failure case, add an iot_configs.h file containing the SSID and password for a wifi network.
[port_bug.zip](https://github.com/arduino-libraries/WiFi101/files/1203748/port_bug.zip)

The url in the attached code may be used for troubleshooting this problem; I'll keep it live for a while.
 
Edit: I know this is an unlikely-seeming bug, so I hope I didn't provoke it with a mistake somewhere else. I did test the target site with AMQP and MQTT protocols, however.

**Comment by sandeepmistry** [comment]
Hi @JetstreamRoySprowl,

I'm guessing the SSL root certificate used on the ports are not the same as the one on port 443. Please try this guide to add a new root certificate for the non-443 port: https://www.arduino.cc/en/Tutorial/FirmwareUpdater

If that doesn't solve the issue please re-open.
