### ISSUE TITLE
Connection timing out

### ISSUE THREAD

**Issue by driverblock** [arduino-libraries/WiFi101#189]
Not sure if this is an actual issue or a simple hardware problem. Adafruit customer bought 5 M0 WiFi Feathers. Two of the five exhibit the same problem. The other three work using the same code.  Two of five with the same problem seems maybe a little on the unlikely side, so I'm throwing this against the wall...

Forum thread is here.  Sample code is posted there.  
https://forums.adafruit.com/viewtopic.php?f=57&t=122832&p=615483#p613233

Symptoms: 
- WiFi.begin is returning 0. (looking at the library code, this seems to be WL_IDLE_STATUS, and it appears to be the result of a timeout on the connection attempt).
- Customer tried connecting both to a router and to a phone hotspot.  Begin returns 0 from both.
- Router and phone both indicate that the Feather is connected.

**Comment by sandeepmistry** [comment]
@driverblock unless we can reproduce, there's not much we can do for this issue.

Maybe the 2 bad boards had the same MAC address?

If you were able to have the customer send the problem boards back for testing and can reproduce the issue please re-open and let us know what debugging you have done.
