### ISSUE TITLE
Arduino mkr1000 not sending data to web server

### ISSUE THREAD

**Issue by someshvar** [arduino-libraries/WiFi101#192]
HI All !
I am trying to send my Arduino photo cell sensor data to my PHP webpage.The Arduino code is successfully reading sensor data ,connecting to the WiFi network, it is connecting my website but it is not connecting the PHP page :The following code seems to be the problem:
client.println("GET /arduino/test.php?sensorData=" +String(sensorData) + " HTTP/1.1");
The php page is working correctly as i checked it with dummy data. 
Can anybody help?

The arduino code is shown below:

// Libraries
#include <SPI.h>
#include <WiFi101.h>
// Credentials
char ssid[] = "D-Link"; // your network SSID (name)
char pass[] = "secret"; // your network password
int status = WL_IDLE_STATUS; // the Wifi radio's status
char server[] = "advisingmanager.com";
unsigned long lastConnectionTime = 0;
const unsigned long postingInterval = 10L * 10L;
WiFiClient client;
void setup()
{
  Serial.println("in set up function now  ");
  // Serial
  Serial.begin(115200);
  // Attempt to connect to Wifi network:
  while ( status != WL_CONNECTED)
  {
    Serial.println("Attempting to connect to WPA SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network:
    status = WiFi.begin(ssid, pass);
    // Wait 10 seconds for connection:
    delay(1000);
  }
  // you're connected now, so print out the data:
  Serial.println("\nYou're connected to the WiFi network\n");
}
void loop()
{
  if (millis() - lastConnectionTime > postingInterval)
  {
    // Measure light level
    int sensorData = analogRead(A0);
    // Send request
    httpRequest(sensorData);
  }
}
void httpRequest(int sensorData)
{
  
  client.stop();
  if (client.connect(server, 80))
  {     
    **client.print("POST /arduino/test2.php  HTTP/1.1");**
    client.println("Host: advisingmanager.com");
    client.println("Content-Type: application/x-www-form-urlencoded"); 
    **client.print(sensorData);**
    client.println("Connection: close");
    client.println();
    lastConnectionTime = millis();
  }
  else
  {
    // if you couldn't make a connection:
    Serial.println("connection failed");
  }
}

**Comment by sandeepmistry** [comment]
Hi @someshvar,

There are two issues in your sketch above:

1) `client.print("POST /arduino/test2.php HTTP/1.1");`

This should be `client.println(...);` to be HTTP compliant

2) the content you are sending `client.print(sensorData);` is not form URL encoded.

If those are not working, please re-open and maybe you can share the minimal PHP code used on the server side.
