### ISSUE TITLE
Can not scan with access point running

### ISSUE THREAD

**Issue by rafkhan** [arduino-libraries/WiFi101#193]
Is there a way to scan for networks while the access point is enabled? I don't get an error, I just get 0 returned from `scanNetworks()`. Thanks :)

**Comment by sandeepmistry** [comment]
Hi @rafkhan,

This is probably a limitation of the WINC1500 firmware. You can try to contact Microchip/Atmel support to request this feature.

**Comment by rafkhan** [comment]
@sandeepmistry yeah, unfortunately it is :(
