### ISSUE TITLE
A new firmware (v19.5.2 -> v19.5.4): KRACK vulnerability and some TLS fix.

### ISSUE THREAD

**Issue by kbumsik** [arduino-libraries/WiFi101#194]
Hi,
I am currently working on [WINC1500 Wi-Fi driver for an RTOS](https://github.com/RIOT-OS/RIOT/pull/7433) (not related to Arduino though). I just got a news that [Microchip released a new firmware](http://www.microchip.com/design-centers/wireless-connectivity/embedded-wi-fi/wpa2-protocol-vulnerability), responding to [KRACK](https://www.krackattacks.com/) issue ([VU\#228519](https://www.kb.cert.org/vuls/id/228519)). This also includes some issues of WINC1500 firmware, including TLS problems.

This new firmware seems quite important. Microchip haven't released a new driver so all we need to do is updating the firmware. Is Arduino planning to add this firmware to the WiFi101 firmware uploader?

**Comment by kbumsik** [comment]
The discussion of this issue has been done in https://github.com/arduino/Arduino/issues/6834 . And I will close this issue when https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/pull/11 is merged.

**Comment by sandeepmistry** [comment]
I've also created https://github.com/arduino-libraries/WiFi101/pull/195 to update the latest model B firmware check once the new firmware updater has been released.

**Comment by kbumsik** [comment]
Thank you very much for quick response. Out of curiosity, will it be available after the merge or next release of Arduino IDE/WiFi101 library?

**Comment by sandeepmistry** [comment]
Very likely to be in the next IDE release if all testing goes well.

**Comment by sandeepmistry** [comment]
The PR to include the new version of the firmware updater (and firmware release) in the IDE can be here: https://github.com/arduino/Arduino/pull/6840
