### ISSUE TITLE
Can I dynamically set WiFi name and password?

### ISSUE THREAD

**Issue by liuqiyuan** [arduino-libraries/WiFi101#198]
So that I don’t need to recompile.

**Comment by ericbaril72** [comment]
You can even store plenty ssid/pwd combos on an SDcard to maximize internet availability.

This is as a client... as an AP, you may need to restart the AP service

**Comment by sandeepmistry** [comment]
Another way to achieve this is via provisioning mode: https://www.arduino.cc/en/Reference/WiFi101BeginProvision
