### ISSUE TITLE
wpa2 enterprise

### ISSUE THREAD

**Issue by lorenzoromagnoli** [arduino-libraries/WiFi101#199]
Can MKR1000 connect to wpa2 enterprise network like eduroam?

I remember I could do it with the Arduino YUN
http://forum.arduino.cc/index.php?topic=197267.0

**Comment by sandeepmistry** [comment]
@lorenzoromagnoli it looks like it's possible from the ASF code: http://asf.atmel.com/docs/latest/common.components.wifi.winc1500.security_enterprise_network_example.sam4s_xplained_pro/html/main_8c.html

We don't have any API's exposed via the WiFi101 library and have not tested it ...

**Comment by mastrolinux** [comment]
do we have any update on this one? Enterprise customers are starting asking for it in our support channel.

**Comment by adriens** [comment]
Yes, pleeeeaaaazzzz 🙏 😺

**Comment by adriens** [comment]
Thank you @lorenzoromagnoli , I'll give a try on this on my Yun rev2.
