### ISSUE TITLE
UDP read not working on AVR boards

### ISSUE THREAD

**Issue by cmaglie** [arduino-libraries/WiFi101#2]
The example UDPNTPClient returns always `0` as current timestamp.

This means that UDP send is working (because the time server receive the request) but the UDP read is not (because it reads always as `0x00`).

The bug appears only on AVR boards, probably the issue is due to a wrong assumption about datatype size on 8bit MCU.

**Comment by mwernick1** [comment]
I have an arduino WiFi101 shield, and am experiencing this problem.  Is this an AVR device?  I tried increasing socket buffer, but no luck.  Any other ideas?

**Comment by cmaglie** [comment]
@mwernick1 
may you try the patch here https://github.com/arduino-libraries/WiFi101/pull/5

**Comment by cmaglie** [comment]
Not solved, there is still a buggy behaviour.
We are working on this one.

**Comment by sandeepmistry** [comment]
This has been resolved with #7.
