### ISSUE TITLE
For security reasons need a consistent method to obtain the remote IP

### ISSUE THREAD

**Issue by drp0** [arduino-libraries/WiFi101#212]
I consider the recovery of the remote client IP to be a basic security requirement of a server.
Sandeep has come up with a couple of methods for different versions of the YIFI101 library, for which I am greatful.
V1.5 of the library killed my previous method.
I suggest we need a fully supported library call.

For those in urgent need , this is my method for V1.5:
In WiFi.cpp remove "static" from "static void socket_cb(SOCKET sock, uint8 u8Msg, void *pvMsg)"
In WiFi.h move "uint32_t _resolve;" to public from private

In sketch declare..

String theclient = ""; // callback returned remote ip and port
IPAddress rip;            // remote IP;
long rport;                 // remote port
void socket_cb(SOCKET sock, uint8 u8Msg, void *pvMsg);

static void myResolve_cb(uint8_t * /* hostName */, uint32_t hostIp) {
WiFi._resolve = hostIp;
}

void mySocketBufferCb(SOCKET sock, uint8 u8Msg, void *pvMsg) {
socket_cb(sock, u8Msg, pvMsg); // call the original callback
 if( u8Msg == SOCKET_MSG_ACCEPT) {
 tstrSocketAcceptMsg *pstrAccept = (tstrSocketAcceptMsg *)pvMsg;
 rip = pstrAccept->strAddr.sin_addr.s_addr;
 rport = pstrAccept->strAddr.sin_port;
 theclient = String(rip[0]) + "." + String(rip[1]) + "." + String(rip[2]) + "." + String(rip[3]) + ":" +  String(rport);
 }
}

// After connection to the router:
// ********* override the original callbacks **********
 registerSocketCallback(mySocketBufferCb, myResolve_cb);
// ****************************************************
// and before..
server.begin();

"theclient" contains the latest ip and port after client.connected() is true

David

**Comment by sandeepmistry** [comment]
@drp0 please see my comment from https://github.com/arduino-libraries/WiFi101/issues/40#issuecomment-354826461.

PR #207 which has been merged and released in the last library update will allow you to do:

```
client.remoteIP();

and

client.remotePort();
```
