### ISSUE TITLE
How does one customize the provisioning HTML?

### ISSUE THREAD

**Issue by youcangetme** [arduino-libraries/WiFi101#225]
If I was to take this product to the final step of mass production I would want to make the HTML page used during the provisioning / wireless setup to match the product (right now its Arduino specific branding). I have looked around the source code and could not find the source of the HTML.

Can somebody tell me where to find it?

**Comment by sandeepmistry** [comment]
You will need to use an ASF tool to do this.

I suggest contacting Microchip support if you have further questions on this.
