### ISSUE TITLE
Wifi::Disconnect returns M2M_ERR_MEM_ALLOC

### ISSUE THREAD

**Issue by klausj1** [arduino-libraries/WiFi101#228]
My arduino has a somehow poor WiFi connection, which sometimes leads to problems. More details see #180.

To repair these problems, I call `WiFi.disconnect()` if I do not receive an answer.

Every some minutes to every some days the disconnect does not work, and `(WiFi.status() == WL_CONNECTED)` still delivers true.

I digged on as deep as I can. I added an error check in WiFiClass::disconnect(): 

```void WiFiClass::disconnect()
{
	// Close sockets to clean state
    // ToDo: Call WiFiClient::stop for all clients? Only if reproducable
	for (int i = 0; i < MAX_SOCKET; i++) {
		WiFiSocket.close(i);
	}

  sint8 rc = m2m_wifi_disconnect();
  if (rc != M2M_SUCCESS)
  {
      Serial.print("!!! WiFiClass::disconnect: Error when disconnecting WiFi! Errorcode: ");
      Serial.println(rc);
  }

#ifdef CONF_PERIPH
	// WiFi led OFF (rev A then rev B).
	m2m_periph_gpio_set_val(M2M_PERIPH_GPIO15, 1);
	m2m_periph_gpio_set_val(M2M_PERIPH_GPIO4, 1);
#endif
}
```

 and found out that
+ m2m_wifi_disconnect() always returns -3 (M2M_ERR_MEM_ALLOC) if I have this problem
+ The problem always happens after a connect via HTTPS goes wrong (In `WiFiSocketClass::connect`, the socket state is `SOCKET_STATE_CONNECTING` until the 20 seconds timeout is reached); This connect is only done when there WiFi was disconnected before.
+ If I call `WiFi.end()`, the state goes to disconnected, and my sketch can continue.

I tried to reproduce this behaviour, but I failed (I could not set up an HTTPS-connection to a webserver in my own network, because  I cannot download my self-signed certificate, see https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/issues/10).

It seems I am not completely alone with this problem: https://www.avrfreaks.net/forum/winc1500-https-dns-lookup-error.

Any ideas? I assume this is more an Atmel problem than a problem of the WiFi Library.

Regards,
Klaus

**Comment by sandeepmistry** [comment]
@klausj1 I would suggest you report this issue to Atmel/Microchip support, and let us know of the support ticket number here so we can follow up.

**Comment by klausj1** [comment]
@sandeepmistry, can you please provide me a concrete link for the Atmel/Microchip support? I googled around a bit, but I am not sure where to start.

Thanks, Klaus

**Comment by PKGeorgiev** [comment]
@klausj1 this should be the link: http://www.microchip.com/support/hottopics.aspx

**Comment by sandeepmistry** [comment]
I'm closing this for now due to lack of feedback, please re-open with any progress to restart the discussion if you are still interested.
