### ISSUE TITLE
mkr1000 ap udp multiple connections

### ISSUE THREAD

**Issue by PieroProcessing** [arduino-libraries/WiFi101#233]
HI, 
I started with mkr1000 an access point to send udp data. it works fine but after one connection is established I can't connect any other machine through wifi on it. Is it a common problem?

**Comment by sandeepmistry** [comment]
Hi @PieroProcessing,

This is related to https://github.com/arduino-libraries/WiFi101/issues/46.

You'll need to call `.begin(...)` on the `WiFiUDP` instance again, as the firmware doesn't automatically bind the sockets when a connection is lost.

**Comment by sandeepmistry** [comment]
Hi @PieroProcessing, did you have a chance to try my suggestion?

**Comment by PieroProcessing** [comment]
I found a solution. It s pretty raw but it works.
https://github.com/PieroProcessing/MKR1000-Osc-Upd/blob/master/WiFiUdpSendReceiveRawOscMkr1000.ino

Il mer 18 set 2019, 19:53 Sandeep Mistry <notifications@github.com> ha
scritto:

**Comment by sandeepmistry** [comment]
Ok, then let's close this for now.
