### ISSUE TITLE
problems...

### ISSUE THREAD

**Issue by HACKER-3000** [arduino-libraries/WiFi101#234]
In file included from C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/common/include/nm_common.h:45:0,

                 from C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/socket/include/socket.h:60,

                 from C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/WiFiClient.h:28,

                 from C:\Users\arvid\Documents\Arduino\libraries\ESP8266MQTTClient\src/ESP8266MQTTClient.h:29,

                 from C:\Users\arvid\Documents\Arduino\Esp8266weather\Esp8266weather.ino:1:

C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/bsp/include/nm_bsp.h:110:23: error: conflicting declaration 'typedef long unsigned int uint32'

 typedef unsigned long uint32;

                       ^

In file included from C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/esp8266_peri.h:24:0,

                 from C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/Arduino.h:38,

                 from sketch\Esp8266weather.ino.cpp:1:

C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1/tools/sdk/include/c_types.h:49:29: error: 'uint32' has a previous declaration as 'typedef unsigned int uint32'

 typedef unsigned int        uint32;

                             ^

In file included from C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/common/include/nm_common.h:45:0,

                 from C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/socket/include/socket.h:60,

                 from C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/WiFiClient.h:28,

                 from C:\Users\arvid\Documents\Arduino\libraries\ESP8266MQTTClient\src/ESP8266MQTTClient.h:29,

                 from C:\Users\arvid\Documents\Arduino\Esp8266weather\Esp8266weather.ino:1:

C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/bsp/include/nm_bsp.h:133:22: error: conflicting declaration 'typedef long int sint32'

 typedef signed long  sint32;

                      ^

In file included from C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/esp8266_peri.h:24:0,

                 from C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/Arduino.h:38,

                 from sketch\Esp8266weather.ino.cpp:1:

C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1/tools/sdk/include/c_types.h:52:29: error: 'sint32' has a previous declaration as 'typedef int sint32'

 typedef signed int          sint32;

                             ^

In file included from C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\ESP8266WiFi\src/WiFiClientSecure.h:25:0,

                 from C:\Users\arvid\Documents\Arduino\libraries\ESP8266MQTTClient\src/ESP8266MQTTClient.h:30,

                 from C:\Users\arvid\Documents\Arduino\Esp8266weather\Esp8266weather.ino:1:

C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\ESP8266WiFi\src/WiFiClient.h:40:7: error: redefinition of 'class WiFiClient'

 class WiFiClient : public Client, public SList<WiFiClient> {

       ^

In file included from C:\Users\arvid\Documents\Arduino\libraries\ESP8266MQTTClient\src/ESP8266MQTTClient.h:29:0,

                 from C:\Users\arvid\Documents\Arduino\Esp8266weather\Esp8266weather.ino:1:

C:\Users\arvid\Documents\Arduino\libraries\WiFi101\src/WiFiClient.h:31:7: error: previous definition of 'class WiFiClient'

 class WiFiClient : public Client {

       ^

In file included from C:\Users\arvid\Documents\Arduino\libraries\ESP8266MQTTClient\src/ESP8266MQTTClient.h:30:0,

                 from C:\Users\arvid\Documents\Arduino\Esp8266weather\Esp8266weather.ino:1:

C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\ESP8266WiFi\src/WiFiClientSecure.h:34:3: error: 'WiFiClientSecure::~WiFiClientSecure()' marked override, but does not override

   ~WiFiClientSecure() override;

   ^

C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\ESP8266WiFi\src/WiFiClientSecure.h:37:7: error: 'int WiFiClientSecure::connect(String, uint16_t)' marked override, but does not override

   int connect(const String host, uint16_t port) override;

       ^

C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\ESP8266WiFi\src/WiFiClientSecure.h:45:10: error: 'size_t WiFiClientSecure::write_P(const char*, size_t)' marked override, but does not override

   size_t write_P(PGM_P buf, size_t size) override;

          ^

C:\Users\arvid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\ESP8266WiFi\src/WiFiClientSecure.h:50:10: error: 'size_t WiFiClientSecure::peekBytes(uint8_t*, size_t)' marked override, but does not override

   size_t peekBytes(uint8_t *buffer, size_t length) override;

          ^

**Comment by sandeepmistry** [comment]
Hi @HACKER-3000,

The WiFi101 library is not compatible with the ESP8266.
