### ISSUE TITLE
DHCP options

### ISSUE THREAD

**Issue by blainemulugeta** [arduino-libraries/WiFi101#241]
Is there anyway to configure the DHCP options sent in the DHCP transaction? 

Example: is there a DHCP client function that set's those options? or a file ... please help trying to add DHCP option 161 to DHCP DISCOVER message on the Adafruit Feather M0..any insight would be greatly appreciated! 

Thank you!

**Comment by sandeepmistry** [comment]
Hi @blainemulugeta,

I don't believe the firmware on the WINC1500 supports this feature. I suggest you contact Microchip technical support by creating a new support ticket on the following page: http://www.microchip.com/technical-support/hot-topics

**Comment by sandeepmistry** [comment]
We have no plans to support this feature at this time, so I'm closing and marking as won't fix for now.
