### ISSUE TITLE
Reducing TCP_SOCK_MAX below 7 causes UDP broadcast to stop working

### ISSUE THREAD

**Issue by jrowberg** [arduino-libraries/WiFi101#242]
I've recently narrowed down a strange failure case to what appears to be a bug in this library, though it may be in the underlying code from Atmel. I'm not sure yet. Basically, I have a SAMD21-based design with a bunch of peripherals, including the ATWINC1500 for wifi. I modified the WiFi101 library to use static allocation instead of dynamic allocation for socket buffers in order to have a more deterministic answer for memory usage, and I simultaneously reduced the `TCP_SOCK_MAX` and `UDP_SOCK_MAX` values to 2 and 1 respectively because that's all I need. This saves a great deal of SRAM when using static allocation, since only three ~1400-byte buffers are created instead of 11 (defaults are 7 and 4 for those MAX values, respectively).

The application uses a custom UDP broadcast message (255.255.255.255) after connecting to an AP to let other devices on the network know where it is, and starts a TCP server socket to wait for incoming connections. It's pretty straightforward. However, I found that when I reduced the socket counts, I stopped receiving UDP broadcasts on my test machine. My custom test app first failed, so I tried Wireshark, and it too showed no UDP broadcast packets. So then I sniffed the module's SPI lines with a logic analyzer, and lo and behold there's no data whatsoever going between MCU and module when UDP packets are supposed to be sent. TCP connections still seem to work fine.

I simplified the failure case by reverting back to the stock v0.15.2 library code with none of my mods, then applying them individually until the problem re-appeared. It turns out that all you have to do is change `TCP_SOCK_MAX` from 7 to anything less than 7:

https://github.com/arduino-libraries/WiFi101/blob/master/src/socket/include/socket.h#L119

Reducing `UDP_SOCK_MAX` even all the way down to 1 while leaving `TCP_SOCK_MAX` intact still works fine. It is not necessary to use any TCP features at all in order to demonstrate the issue. My static-allocation mod makes no difference.

The following example sketch is enough. **NOTE** you will need the standard `WiFi.setPins(...)` call if you have custom connections, and you will also need the `arduino_secrets.h` file that other examples have. It's simplest to just open an existing example and then copy and paste this code right into the main sketch tab.

```
#include <SPI.h>
#include <WiFi101.h>
#include <WiFiUdp.h>

#define UDP_PORT 1234

int status = WL_IDLE_STATUS;
#include "arduino_secrets.h" 
///////please enter your sensitive data in the Secret tab/arduino_secrets.h
char ssid[] = SECRET_SSID;        // your network SSID (name)
char pass[] = SECRET_PASS;    // your network password (use for WPA, or use as key for WEP)

WiFiUDP udp;

void setup() {
  //Initialize serial and wait for port to open:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  // check for the presence of the shield:
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue:
    while (true);
  }

  // attempt to connect to WiFi network:
  while ( status != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    status = WiFi.begin(ssid, pass);

    // wait 10 seconds for connection:
    delay(5000);
  }
  Serial.println("Connected to wifi");
  printWiFiStatus();

  Serial.println("\nStarting UDP socket");
  udp.begin(UDP_PORT);
}

int lastSec = -1;
int sec = 0;
uint8_t buf[] = { 0x01, 0x02, 0x03, 0x04 };

void loop() {
  sec = millis() / 1000;
  if (lastSec != sec) {
    lastSec = sec;
    Serial.print("Sending broadcast packet @ time "); Serial.println(sec);
    udp.beginPacket(IPAddress(255, 255, 255, 255), UDP_PORT);
    udp.write(buf, 4);
    udp.endPacket();
  }
}

void printWiFiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}
```

If `TCP_SOCK_MAX` is left at 7, everything works great. You can see the 4-byte broadcast packets on any device capable of receiving UDP broadcast on the same network. But if you change `TCP_SOCK_MAX` to 6, it stops working.

With some additional troubleshooting, I've determined the following interesting tidbits. First, the `WiFiUDP.endPacket()` method returns 0 (failure) only in the case where `WiFiSocket.sendto()` returns < 0. However, the `sendto()` method returns *exactly* 0 in the case where the socket is not bound:

https://github.com/arduino-libraries/WiFi101/blob/master/src/utility/WiFiSocket.cpp#L322

This allows `endPacket()` to indicate success after `sendto()` indicates failure, and should (probably?) be considered a bug. A simple fix is to change the condition in the `endPacket()` call to be `<=` instead of `<`:

https://github.com/arduino-libraries/WiFi101/blob/master/src/WiFiUdp.cpp#L140

This discovery revealed that the UDP socket in my failing test case is (at least in some circumstances) NOT ending up in the BOUND state. I have no idea why, since previous calls up to that point always indicate success as far as I can tell.

Related investigation into state-modifying code also revealed what appears to be another bug, unless I misunderstand something: the socket state and parent values are only initialized post-creation when the socket handle is > 0, but 0 is a valid handle and will always be used for the first TCP socket:

https://github.com/arduino-libraries/WiFi101/blob/master/src/utility/WiFiSocket.cpp#L69

Shouldn't that condition be `if (sock >= 0)` instead?

I have a J-Link debugger and GDB GUI available, and I'm happy to dig further if someone can point me in the right direction. So far, I haven't been able to determine the problem. Any ideas?

**Comment by sandeepmistry** [comment]
Hi @jrowberg,

So the WINC1500 firmware is expecting UDP sockets to start at 7, see this line that is part of the Atmel ASF source:  https://github.com/arduino-libraries/WiFi101/blob/0374eb5661ad85ded096048b0f3a98dd016ccdbc/src/socket/source/socket.c#L576

You can change this line to  `sock = (SOCKET)(u8SockID + 7);`

Does this help?

**Comment by jrowberg** [comment]
> Would you like to submit a pull requests for the changes you suggested in [#242 (comment)](https://github.com/arduino-libraries/WiFi101/issues/242#issue-362265351) ?

Sure, I'll do that shortly.

**Comment by awatterott** [comment]
There is also a new WINC1500 firmware and host driver version: `19.6.1`. Maybe it is fixed here.
Release notes: http://ww1.microchip.com/downloads/en/DeviceDoc/ATWINC15x0%20Software%20Release%20Notes_9%20Aug%202018.pdf

**Comment by sandeepmistry** [comment]
Closing this for now based on the comment in https://github.com/arduino-libraries/WiFi101/pull/247#issuecomment-532774765.
