### ISSUE TITLE
Remove plain http example

### ISSUE THREAD

**Issue by mastrolinux** [arduino-libraries/WiFi101#248]
We are going to dismiss plain http in our main domain, so please update https://github.com/arduino-libraries/WiFi101/blob/c2830f866562e7bea5e510f68e618f044957b543/examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino#L96 to use https://www.arduino.cc/asciilogo.txt instead of http://arduino.cc/asciilogo.txt

**Comment by facchinm** [comment]
Moving to example.org looks better than forcing https on the simplest example (with all the certificates headache associated)
