### ISSUE TITLE
Using WiFi101 shield in low power mode

### ISSUE THREAD

**Issue by Walter82** [arduino-libraries/WiFi101#25]
Hello,
Is there a possibility to switch off the WiFi101 shield in software? For example: 
digitalWrite(5, LOW); - reduces the power consumption significantly (90%). After that I execute 
WiFi.init(); 
WiFi.begin(_ssid, _pass);
The WiFi connection is established. But:
WiFiClient client = WiFiClient();
client.connect(host, port); - is not working.

Maybe there is another possibility to switch off the WiFi101 shield in software?
Thank you very much and best regards, Walter

**Comment by ThibaultRichard** [comment]
To shutdown WINC you have to put high chipen pin.
Beware to completely reinit wifi lib after doing that (it does a specific power up sequence with chipen and resetn)

Sent from my iPhone

On Jan 21, 2016, at 6:07 PM, "Walter82" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
Is there a possibility to switch off the WiFi101 shield in software? For example:
digitalWrite(5, LOW); - reduces the power consumption significantly (90%) After that I execute
WiFiinit();
WiFibegin(_ssid, _pass);
The WiFi connection is established But:
WiFiClient client = WiFiClient();
clientconnect(host, port); - is not working

Maybe there is another possibility to switch off the WiFi101 shield in software?
Thank you very much and best regards, Walter

**Comment by Walter82** [comment]
>you have to put high chipen pin - done.
>Beware to completely reinit wifi lib after doing that - done.
WiFi.init();
WiFi.begin(_ssid, _pass); -> the wifi connection is there.
Problem: client.connect(host, port); - is not working.

**Comment by agdl** [comment]
@Walter82 maybe you can be interested in https://github.com/arduino-libraries/WiFi101/pull/49

**Comment by sandeepmistry** [comment]
This feature has been added in #49, which will be available in the next release.
