### ISSUE TITLE
SSL Verification Bypass help needed

### ISSUE THREAD

**Issue by gjt211** [arduino-libraries/WiFi101#256]
After some digging (and yes I have no idea what I am doing) I have discovered a flag that should allow me to use SSL but bypass the certificate verification.
The flag name is `SO_SSL_BYPASS_X509_VERIF`
I found it in socket.c
https://github.com/arduino-libraries/WiFi101/blob/0fbb49dd2453340913a6e67721199dfe905aedcf/src/socket/source/socket.c#L1167
and also at
https://github.com/arduino-libraries/WiFi101/blob/0fbb49dd2453340913a6e67721199dfe905aedcf/src/socket/include/socket.h#L183

What I would like to know is how to set this flag in my Arduino code.
I am also wondering if this will actually work?
By this I mean will the SSL connection will be successful without having the certificate in the WINC1500?
Yes I am aware of the security issues this raises but at this point in time that is not relevant to what I need.

Any help is appreciated.

**Comment by gjt211** [comment]
Any ideas anyone please?

**Comment by sandeepmistry** [comment]
Hi @gjt211,

I suggestion you contact Microchip/Atmel support for this question.
