### ISSUE TITLE
ez support for low power sleep mode (w/code)

### ISSUE THREAD

**Issue by ladyada** [arduino-libraries/WiFi101#26]
this is an easy fix, see 
https://github.com/adafruit/Adafruit_WINC1500/commit/0e250139fbaa81221cac9af4786ccd6009290227
and second half of 
https://github.com/adafruit/Adafruit_WINC1500/commit/08ad733f4e822888f38e3657f4b20d4b9b2c7f64

this lets you go from 90mA to 10mA with no real change in functionality, see powergraphs here
https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/power-management#power-usage-and-saving-with-wifi

**Comment by sandeepmistry** [comment]
Hi @ladyada,

Thanks for the links! We've added some new API's for low power modes in #49. They will be available in the next release.
