### ISSUE TITLE
arduino 1.8.8 firmware updater does not show new firmware version

### ISSUE THREAD

**Issue by novski** [arduino-libraries/WiFi101#261]
My arduino firmware updater from Arduino1.8.8 does not show the newest firmware version.
Im running a firmware uploader skript from the examples for adafruit Feather M0 and walked through [this tutorial](https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/updating-firmware). 
I have updated the Library to Wifi101 0.15.3.
But the dropdown for firmware version is only populated with one version and that seams outdated. Its called: WINC1501 Model A (19.**4**.4) (Arduino Wifi 101 Shield). The firmware checker does not pass because the newest firmware version checked for is 19.**5**.4.  it recognizes the 19.**4**.4.
How can i get the newest firmware version?

**Comment by rsispal** [comment]
I found the same thing with a number of WINC1500 breakouts. For this firmware upgrade process, I downgraded Arduino IDE to 1.8.7 and then use 1.8.8 for actual development.

**Comment by sandeepmistry** [comment]
This should be solved with the latest firmware updater version.
