### ISSUE TITLE
Cannot Connect to .gov Domains with SSL

### ISSUE THREAD

**Issue by nheffronneuhold** [arduino-libraries/WiFi101#262]
I have a program I'm working on that used to connect to a .gov domain through SSL without problem and recently it stopped working. I went back to the simplest example I could without success.

I am using the WiFiSSLClient example sketch and although I can get it to connect to any .com domain I try, I cannot get it to connect to .gov domains. The one I want is www.aviationweather.gov, but I've tried several .gov's without any success. I suspect that it must be due to a recent update to the library since I had it working before and it just stopped within the last couple months.

I am using an Adafruit Feather M0 WiFi - ATSAMD21 + ATWINC1500

```
#include <SPI.h>
#include <WiFi101.h>

#include "arduino_secrets.h" 
///////please enter your sensitive data in the Secret tab/arduino_secrets.h
char ssid[] = SECRET_SSID;        // your network SSID (name)
char pass[] = SECRET_PASS;    // your network password (use for WPA, or use as key for WEP)
int keyIndex = 0;            // your network key Index number (needed only for WEP)

int status = WL_IDLE_STATUS;
// if you don't want to use DNS (and reduce your sketch size)
// use the numeric IP instead of the name for the server:
//IPAddress server(74,125,232,128);  // numeric IP for Google (no DNS)
char server[] = "www.aviationweather.gov";    // name address for Google (using DNS)

// Initialize the Ethernet client library
// with the IP address and port of the server
// that you want to connect to (port 80 is default for HTTP):
WiFiSSLClient client;

void setup() {
  WiFi.setPins(8,7,4,2);
  
  //Initialize serial and wait for port to open:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  // check for the presence of the shield:
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue:
    while (true);
  }

  // attempt to connect to WiFi network:
  while (status != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    status = WiFi.begin(ssid, pass);

    // wait 10 seconds for connection:
    delay(10000);
  }
  Serial.println("Connected to wifi");
  printWiFiStatus();

  Serial.println("\nStarting connection to server...");
  // if you get a connection, report back via serial:
  if (client.connect(server, 443)) {
    Serial.println("connected to server");
    // Make a HTTP request:
    client.println("GET / HTTP/1.1");
    client.println("Host: www.aviationweather.gov");
    client.println("Connection: close");
    client.println();
  }
}

void loop() {
  // if there are incoming bytes available
  // from the server, read them and print them:
  while (client.available()) {
    char c = client.read();
    Serial.write(c);
  }

  // if the server's disconnected, stop the client:
  if (!client.connected()) {
    Serial.println();
    Serial.println("disconnecting from server.");
    client.stop();

    // do nothing forevermore:
    while (true);
  }
}


void printWiFiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}
```

**Comment by dojyorin** [comment]
I do not know if this is the cause, but recently I failed to connect https.

Since `WiFi.getTime ()` is `0', I think that it failed in verification of the certificate validity period.

And it is said that WINC1500 gets time from either NTP server `time-c.nist.gov` or `time-d.nist.gov` at startup.

(Since it is specified at the firmware level, it is difficult to change to another NTP server)

**Comment by nheffronneuhold** [comment]
Have you found any work-around?

**Comment by Rocketct** [comment]
Hi @nheffronneuhold i have tested your sketch using: www.google.com, www.usability.gov, www.benefits.gov, www.usa.gov and with the one shared by you www.aviationweather.gov  and it works.
In my setup i have used a Arduino MKR1000 as hardware and:
- Added the certificates using the IDE Arduino->tools->WiFi101/WIFININA firmware updater;
- Modified in the sketch the server in `char server[] = "www.aviationweather.gov";` and `client.println("Host:` www.aviationweather.gov");` with the one you need to connect
- Used the last WINC1500 firmware (19.6.1) and last WiFi101 library(0.15.3).

**Comment by Rocketct** [comment]
closed due to lack of feedback, @nheffronneuhold if you need reopen the issue
