### ISSUE TITLE
What is the difference between u8FirmwareMajor and u8DriverMajor?

### ISSUE THREAD

**Issue by cawena** [arduino-libraries/WiFi101#266]
With my arduino sketch I can flash the ATWINC1500 from my SD Card.
Steps:

1. Get version info from wifi (e.g. 19.5.2)
2. Get firmware info from my server (19.5.4)
3. download firmware from my server.
4. set ATWINC1500 to download mode
5. erase flash
6. Write to flash

When I check now after flashing, I get **-Err-**
I restart the arduino and all is fine, version is **19.5.4**.
In wifi.cpp I found following code:

```
	if (rev.u8FirmwareMajor != rev.u8DriverMajor && rev.u8FirmwareMinor != rev.u8DriverMinor) {
		sprintf(_version, "-Err-");
	}
	else {
		sprintf(_version, "%d.%d.%d", rev.u8FirmwareMajor, rev.u8FirmwareMinor, rev.u8FirmwarePatch);
	}
```
What is the difference between u8FirmwareMajor and u8DriverMajor?

How can I check the firmware version directly after flashing the new software?

**Comment by sandeepmistry** [comment]
Hi @cawena, I suggest you contact Microchip/Atmel support to get an answer for this.
