### ISSUE TITLE
access point demo (w/code)

### ISSUE THREAD

**Issue by ladyada** [arduino-libraries/WiFi101#27]
a simple little ad-hoc demo sketch:

https://github.com/adafruit/Adafruit_WINC1500/blob/master/examples/AP_SimpleWebServer/AP_SimpleWebServer.ino

**Comment by cmaglie** [comment]
Thank you!

**Comment by zeesh1979** [comment]
for me, wifi.status() doesnt change and it keeps on returning number 3 no matter what is the status of wifi
