### ISSUE TITLE
[WiFiSSLClient] can't connect to maker.ifttt.com:443

### ISSUE THREAD

**Issue by sandeepmistry** [arduino-libraries/WiFi101#270]
See discussion in https://github.com/arduino-libraries/ArduinoHttpClient/issues/62.

Even though the root cert is flashed for `maker.ifttt.com:443`, `WiFiSSLClient` fails to connect.

@Rocketct do you have time to get a Wireshark capture of this?

cc/ @adriens

**Comment by adriens** [comment]
Thanks a lot @sandeepmistry for linking ths issue 👍

**Comment by Rocketct** [comment]
@adriens let me inform you that we are in talk with microchip to support this issue, i'll report as soon as possible

**Comment by adriens** [comment]
Thank you very much @Rocketct  🙏

**Comment by Rocketct** [comment]
hi @adriens with @sandeepmistry have found a fix https://github.com/arduino-libraries/WiFi101/pull/274 could you test and let me know if works on your side ?

**Comment by sandeepmistry** [comment]
Fixed via #274.
