### ISSUE TITLE
Explicit FTPS support?

### ISSUE THREAD

**Issue by tuloski** [arduino-libraries/WiFi101#271]
Reformulating....
Any idea on how to support explicit ftps with this library?
The idea is being able to connect without SSL, send "AUTH SSL" command in clear and then switch to SSL connection, but I'm having hard time to do it because either I connect with a SSL client or without SSL.

**Comment by sandeepmistry** [comment]
Hi @tuloski,

This would not be supported by this library, the same `WiFiClient` underlying socket can't be converted to an SSL connection.

You might have some luck using a WiFiClient with some lower level functions of ArduinoBearSSL: https://github.com/arduino-libraries/ArduinoBearSSL

**Comment by tuloski** [comment]
> This would not be supported by this library, the same `WiFiClient` underlying socket can't be converted to an SSL connection.

How not? There is connectSSL(). Do you mean it cannot be converted on the fly, i.e. connect in clear and then switch to SSL?

**Comment by sandeepmistry** [comment]
> Do you mean it cannot be converted on the fly, i.e. connect in clear and then switch to SSL?

Correct, as far as I know the WINC1500 firmware and SDK provided by Microchip/Atmel does not support thing.
