### ISSUE TITLE
Mac addresses returned in reverse order in examples

### ISSUE THREAD

**Issue by drp0** [arduino-libraries/WiFi101#31]
Just in case for some bizarre reason it is different in other parts of the planet I have to state that I am using the shield in the uk.
My router reports that the mac address of the shield and of itself is in the reverse order of that shown in the example sketches.
Simply printing the mac address in the reverse order solves the issue:
`  byte mac[6];
  WiFi.macAddress(mac);
  Serial.print("MAC address: ");
  Serial.print(mac[0], HEX);
  Serial.print(":");
  Serial.print(mac[1], HEX);
  Serial.print(":");
  Serial.print(mac[2], HEX);
  Serial.print(":");
  Serial.print(mac[3], HEX);
  Serial.print(":");
  Serial.print(mac[4], HEX);
  Serial.print(":");
  Serial.println(mac[5], HEX);`

David

**Comment by agdl** [comment]
I pushed the fix thank you!
