### ISSUE TITLE
MKR1000 no connection with SSL (https)

### ISSUE THREAD

**Issue by Rattenjunge** [arduino-libraries/WiFi101#342]
Hi. I'm new to arduino but I'm pretty sure I did all the steps correctly.

I updated the firmware.
```
WiFi101 firmware check.
WiFi101 shield: DETECTED
Firmware version installed: 19.6.1
Latest firmware version available : 19.6.1

Check result: PASSED
```

I added the certificats with the tool.
![234](https://github.com/arduino-libraries/WiFi101/assets/26927982/3c827f81-cfad-429d-aabf-20f7613161e0)

But still, after running the WifiSSL Client sketch, I will aways get:

```
Connected to wifi
SSID: XXXX
IP Address: XXX.XXX.XXX.XXX
signal strength (RSSI):-52 dBm

Starting connection to server...

disconnecting from server.
```

Hope you can help.

Because I'm using your WifiSSLClient.ino I'm not posting the sketch.

**Comment by per1234** [comment]
Hi @Rattenjunge. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
