### ISSUE TITLE
v0.8.0 does not work with the Uno + WiFi 101Shield

### ISSUE THREAD

**Issue by sandeepmistry** [arduino-libraries/WiFi101#38]
The output of the ```ScanNetworks``` examples is:

```
MAC: F8:F0:5:F0:9A:85
Scanning available networks...
** Scan Networks **
MAC: F8:F0:5:F0:9A:85
Scanning available networks...
** Scan Networks **
MAC: F8:F0:5:F0:9A:85
Scanning available networks...
** Scan Networks **
MAC: F8:F0:5:F0:9A:85
Scanning available networks...
```

even though many access points are in range. Seems to be related to a change introduced in https://github.com/arduino-libraries/WiFi101/commit/f558ef50698aa891d188015904e1148afef44a45. Reverting to v0.7.0, the example is fine.

**Comment by xarvey** [comment]
Same issue here, revert it back works 
https://forum.arduino.cc/index.php?topic=380311.0

**Comment by sandeepmistry** [comment]
@xarvey I've submitted #39 to resolve this.
