### ISSUE TITLE
WEP/WPA Access Point creation support?

### ISSUE THREAD

**Issue by nekhbet** [arduino-libraries/WiFi101#42]
Are there any plans for WEP/WPA Access Point creation support ?

**Comment by sandeepmistry** [comment]
@nekhbet the WINC1500 firmware currently only supports creating access points that are open or have a WEP password.

I've added new API's to create access points with a WEP password in #43.

**Comment by sandeepmistry** [comment]
Closing via #43. Only creating WEP access points will be supported for now as the firmware doesn't currently support WPA.
