### ISSUE TITLE
WiFi101 should probably have user-config GPIO

### ISSUE THREAD

**Issue by ladyada** [arduino-libraries/WiFi101#57]
https://github.com/arduino-libraries/AzureIoT/pull/9#issuecomment-207577372

**Comment by trlafleur** [comment]
Yes, this is need to expose pins to the application level...

Thanks

**Comment by sandeepmistry** [comment]
Yes, for others the pull request for this can be found in #58. We are looking for feedback from the community before merging. Please try it out and let us know.
