### ISSUE TITLE
How to stop AP?

### ISSUE THREAD

**Issue by javorosas** [arduino-libraries/WiFi101#61]
There's a `beginAP` method, but how can I change back to STA mode? I want to connect to a WiFi network after receiving the ssid and password.

Thanks

**Comment by sandeepmistry** [comment]
Hi @javorosas, this functionality is currently missing. However, I have submitted #62 to add it.

The patch includes a new ```WiFi.end()``` API to stop AP mode.

**Comment by javorosas** [comment]
Looks great! Will it work the other way around? Changing from STA to AP mode?

**Comment by sandeepmistry** [comment]
@javorosas thanks for trying!

> Will it work the other way around? Changing from STA to AP mode?

Yes, I have just tested it. Please let me know if it also works for you.

**Comment by sandeepmistry** [comment]
This is closed now that @agdl has merged #62.
